/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Cards: typeof import('./src/components/cards/cards.vue')['default']
    Carousel: typeof import('./src/components/home/carousel.vue')['default']
    Contact: typeof import('./src/components/contact/contact.vue')['default']
    ContactForm: typeof import('./src/components/contact/contactForm.vue')['default']
    Dashboard: typeof import('./src/components/dashboard/dashboard.vue')['default']
    Features: typeof import('./src/components/features/features.vue')['default']
    FeaturesCard: typeof import('./src/components/cards/featuresCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home/home.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Introduction: typeof import('./src/components/introducktion/introduction.vue')['default']
    Payment: typeof import('./src/components/payment/payment.vue')['default']
    'Payment2.': typeof import('./src/components/payment/payment2..vue')['default']
    PaymentForm: typeof import('./src/components/payment/paymentForm.vue')['default']
    PaymentTwo: typeof import('./src/components/payment/paymentTwo.vue')['default']
    Pricing: typeof import('./src/components/pricing/pricing.vue')['default']
    ProductCard: typeof import('./src/components/cards/productCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessModal: typeof import('./src/components/modals/successModal.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WhyPg: typeof import('./src/components/whyPg/whyPg.vue')['default']
  }
}
